version: "3"

services:
  web:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app
    ports:
      - "3000:3000"
    environment:
      - JFROG_NPM_REPOSITORY
      - JFROG_USERNAME
      - JFROG_TOKEN
