version: "3"

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    tty: true
    stdin_open: true
    volumes:
      - ../..:/workspaces:cached
      - ..:/var/app
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - JFROG_NPM_REPOSITORY
      - JFROG_USERNAME
      - JFROG_TOKEN
